name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get npm version from package.json
        id: npm-version
        run: |
          # 从 packageManager 字段提取 npm 版本
          VERSION=$(grep -o 'npm@[0-9\.]*' package.json | cut -d@ -f2)
          echo "npm_version=$VERSION" >> $GITHUB_ENV
          echo "node_version=$(node -v | cut -dv -f2)" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 使用从 package.json 提取的 node 版本（若存在）
          node-version: ${{ steps.npm-version.outputs.node_version || '22' }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci  # 基于 package-lock.json 进行确定性安装

      - name: Build VuePress site
        run: npm run docs:build
      - name: Push URLs to IndexNow
        run: |
          pip install requests
          python .github/scripts/push_to_indexnow.py
        
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
